apiVersion: v1
kind: Namespace
metadata:
  name: ${PUBSUB_PREFIX}-pipeline
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: separation
  namespace: ${PUBSUB_PREFIX}-pipeline
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: melody
  namespace: ${PUBSUB_PREFIX}-pipeline
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: asr
  namespace: ${PUBSUB_PREFIX}-pipeline
