apiVersion: batch/v1
kind: Job
metadata:
  name: separation-job
  namespace: ${PUBSUB_PREFIX}-pipeline
spec:
  backoffLimit: 1
  template:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: ${PUBSUB_PREFIX}-separation@${GCP_PROJECT}.iam.gserviceaccount.com
    spec:
      restartPolicy: Never
      serviceAccountName: separation
      containers:
        - name: separation
          image: ${REGION}-docker.pkg.dev/${GCP_PROJECT}/${ARTIFACT_REPO}/separation:${IMAGE_TAG}
          args:
            - "--id"
            - "${JOB_ID}"
            - "--infile"
            - "gs://${GCS_BUCKET}/stems/${JOB_ID}/mix.wav"
            - "--out"
            - "/tmp/partials"
          env:
            - name: GCS_BUCKET
              value: ${GCS_BUCKET}
            - name: PUBSUB_OUT
              value: ${PUBSUB_PREFIX}-analyze
          volumeMounts:
            - name: partials
              mountPath: /tmp/partials
      volumes:
        - name: partials
          emptyDir: {}
